### ISSUE TITLE
🐛 The first title is not displayed in the sidebar

### ISSUE THREAD

**Issue by LucaModric** [markbattistella/docsify-auto-headers#10]
### Describe the bug

when i set sidebar:true,The first title is not displayed in the sidebar
![image](https://github.com/markbattistella/docsify-auto-headers/assets/27324489/2013dbba-d352-400a-a896-993cdb789fcc)

### Reproduction steps

when my MD only have Heading 1,the style in MD  is 1.Heading ,2.Heading 1,3.Heading 。。。。。；but the sidebar style is  2.Heading 1,3.Heading 。。。。。,the 1.Heading is missing.

### Expected behaviour

.

### Device information

.

### Additional information

.

### Logs and error messages

```shell
.
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by markbattistella** [comment]
Hi @LucaModric - did you have a demo site where I could see the source markdown files? It should simply take whatever is in the existing body markdown (without the plugin) headings and then add the numbering there. If I could see your source then I could see if it is a bug or lack of explanation from me.

**Comment by LucaModric** [comment]
> Hi @LucaModric - did you have a demo site where I could see the source markdown files? It should simply take whatever is in the existing body markdown (without the plugin) headings and then add the numbering there. If I could see your source then I could see if it is a bug or lack of explanation from me.



> Hi @LucaModric - did you have a demo site where I could see the source markdown files? It should simply take whatever is in the existing body markdown (without the plugin) headings and then add the numbering there. If I could see your source then I could see if it is a bug or lack of explanation from me.

[demo.zip](https://github.com/user-attachments/files/16069545/demo.zip)

The issue shown in my screenshot is on demo1.md;

Another question，When my title content is relatively long, the first level title is not a good choice,so my article style will look like demo2.md;but The display on demo2.md like this:
0.1. heading 2
0.2. heading 2
0.3. heading 2

Can demo2.md be displayed like this:
1. heading 2
2. heading 2
3. heading 2
The maximum title level is Title 1, which is prefixed with 1;
The maximum title level is Title 2, which is prefixed with 1;
………………

**Comment by markbattistella** [comment]
Thanks for sending that though - made it easier to understand.

**Demo 1 issue:**

The issue you're facing here is that you're using a pre-build `_sidebar.md` file. What that means is that the `H1` element is actually the `- [demo1](pages/demo1.md)` label. This is directly related to the `subMaxLevel` config item.

As an example, this is what it looks like for me when I set the `subMaxLevel` to `6`:

![image](https://github.com/markbattistella/docsify-auto-headers/assets/17962160/c12a099c-41fa-4753-bbb8-438959398764)

And if I update it to be: `subMaxLevel: 1`:

![image](https://github.com/markbattistella/docsify-auto-headers/assets/17962160/9fa62d0b-e21a-4bd2-bd18-eee81f269462)

Which you can see when I set the max headings to only `H1` it uses the labels from the `_sidebar.md` file.

This I assume is if you wanted to have a custom title for a page but longer or alternate one on the page (eg. in the `_sidebar` you could have `🎉 Start here` but as the `H1` in the page it could be `# Step 1: Getting Started`).

> [!NOTE]
> As a result I'm not marking this as a bug since it is working as intended. If you want to have it auto-generate then you will need to not supply a `_sidebar.md` file, or simply set the `loadSidebar` to `true`. We cannot have both this plugin and the in-built Docsify config fighting over the same element.

---

**Demo issue 2:**

Okay, this is a current limitation of the plugin. It has every page to abide by the same rules from the `index.html` config. 

So this means that every heading will be prefixed with the parent heading numbers (`H2` will have `H1`, whereas `H6` will have `H5, `H4`, `H3`, `H2, and `H1`).

If you want `demo2.md` to only have single numbers, then all of them will need to be `H1` elements, not `H2`:

```md
@autoHeader:1

# heading 2
# heading 2
# heading 2
# heading 2
# heading 2
# heading 2
```

But if you want them to be `H2` elements, then they will be prefixed with the first number in the signifier.

However, if there is no found `H1` element, then it does not increment correctly (as it is expecting it).

This is a semi-bug, semi-enhancement at this point. Somewhere in the future I'd like to implements some more tags like this:

```md
<!-- autoHeader:11.22.33.44.55.66 start:2 finish:4 -->
```

This way each page could be unique to target individual pages, and different scopes.

---

If you are happy, I'd like to close this issue and open a new one with your demo 2 enhancement idea, so we're not grouping too many ideas and issues into one.

**Comment by LucaModric** [comment]
> label

Demo 1 issue is indeed not a bug,When I didn't use your plugin, the sidebar still displayed as shown in the screenshot。

you can close this issue .No need to open a new one for  demo 2。Thank you for your answer, I'm just giving a little suggestion，I hope one day your plugin can support more title styles, and even customize title styles
