### ISSUE TITLE
this _sidebar.md invalid

### ISSUE THREAD

**Issue by insoxin** [markbattistella/docsify-auto-headers#6]

**Comment by insoxin** [comment]
![image](https://user-images.githubusercontent.com/19371836/126587434-88a06133-69bf-47cd-8426-2145e621ba48.png)

**Comment by insoxin** [comment]
I added the numbers manually

**Comment by markbattistella** [comment]
@insoxin - are you saying that the `_sidebar.md` isn't getting the numbers?

**Comment by insoxin** [comment]
> @insoxin - 你是说`_sidebar.md`没有得到数字？

Yes, did you test successfully?

**Comment by markbattistella** [comment]
it wasn't designed to add the numbers to the sidebar, only the body - but I can look into it

**Comment by markbattistella** [comment]
@insoxin to give you an update I have a semi working version but there are some bugs that i need to solve before i release. hopefully soon but then it will number the sidebar for you

**Comment by markbattistella** [comment]
Should be fixed in v5.0.0
